# serverless.yml

service: products-service

provider:
  name: aws
  runtime: nodejs16.x
  #  stage: dev
  region: us-east-1
  environment:
    SERVICE_NAME: ${self:service}

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello

# plugins:
#   - serverless-domain-manager
# custom:
#   customDomain:
#     domainName: 'api.nmrony.info' # Change this to your domain.
#     basePath: 'products' # This will be prefixed to all routes
#     stage: ${self:provider.stage}
#     createRoute53Record: true
custom:
  custom:
    stage: ${opt:stage, self:provider.stage}
    domains:
      prod: api.nmrony.info
      staging: staging-api.nmrony.info
      dev: dev-api.nmrony.info
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: true
