service: nmr-guineapig
frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  profile: itcdevs

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: GET
