version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "sam-s3-sqs-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xr3xadp8gmmd"
s3_prefix = "sam-s3-sqs-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceBucketName=\"sam-s3-sqs-lambda-bucket\""
image_repositories = []
