service: nmr-step-functions-hello
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, 'us-east-1'}

package:
  individually: true

functions:
  hello:
    handler: handler.hello
  ciao:
    handler: handler.ciao

stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: "hello"
      definition:
        Comment: "A Hello World example"
        StartAt: HelloWorld
        States:
          HelloWorld:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello"
            Next: CiaoWorld
          CiaoWorld:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-ciao"
            End: true
